### PR TITLE
WIP: Miriah-revamp site

### PR DESCRIPTION
**Pull request by Soypete**
I have added come basic content. 

- [ ]  add links to external
- [ ] .link the pages
- [ ] add table of contents
- [ ] add logos and images
- [ ] add link to Go West site.

### CODE REVIEW

**Comment by clintberry** [comment]
Can you put a screen shot in here so I don't have to build it? #iamlazy

**Comment by Soypete** [comment]
Screen Shot 2019-10-03 at 10 39 57 AM
so the links at the top aren't working... but you can read what they say in files

**Comment by Soypete** [comment]
the links to the social media sites do work

**Comment by clintberry** [comment]
So you are changing the template and going a full new design? I would just wait for the designers for real. Your site looks like an engineer made it.  :-)

**Comment by Soypete** [comment]
@clintberry I want to wait for the designer. I am more concerned with the contents RN. that we have all the words and links we want and stuff. The designer can handle the looks and flows.

**Comment by clintberry** [comment]
good idea. get the copy in there.

**Pull request closed without merging**
